workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic  # koristi Team integration za signing i upload

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: rs.nikolakerkez.fruitcarepro
        # ✅ automatic signing preko integracije, nema team_id ili automatic_signing

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - nikolakerkez.rs@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        inherit: true   # koristi integraciju za autentifikaciju i signing
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false  # ako želiš direktan App Store upload, stavi true


  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2

    environment:
      flutter: stable
      android_signing:
        - keystore_reference

      vars:
        PACKAGE_NAME: "rs.nikolakerkez.fruitcarepro"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Flutter analyze
        script: |
          flutter analyze

      - name: Flutter test
        script: |
          flutter test
        ignore_failure: true

      - name: Build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt

    publishing:
      email:
        recipients:
          - nikolakerkez.rs@gmail.com
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
