workflows:
    android-workflow-id:
      name: Android Workflow auto sign
      max_build_duration: 120
      environment:
        android_signing:
          - keystore_reference
        groups:
          - google_play
        vars:
          PACKAGE_NAME: "rs.nikolakerkez.fruitcarepro"
          GOOGLE_PLAY_TRACK: alpha
        flutter: stable
      scripts:
        - name: Set up local.properties
          script: | 
            echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
        - name: Get Flutter packages
          script: | 
            flutter pub get
        - name: Flutter analyze
          script: | 
            flutter analyze
        - name: Flutter unit tests
          script: | 
            flutter test
          ignore_failure: true
        - name: Build AAB with Flutter
          script: | 
            BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
            flutter build appbundle --release \
              --build-name=1.0.$BUILD_NUMBER \
              --build-number=$BUILD_NUMBER
      artifacts:
        - build/**/outputs/**/*.aab
        - build/**/outputs/**/mapping.txt
        - flutter_drive.log
      publishing:
        email:
          recipients:
            - nikolakerkez.rs@gmail.com
          notify:
            success: true
            failure: false
        google_play:
          credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
          track: $GOOGLE_PLAY_TRACK
          submit_as_draft: true
    ios-workflow:
      name: iOS Workflow auto sign
      max_build_duration: 120
      integrations:
        app_store_connect: CodeMagic
      environment:
        ios_signing:
          distribution_type: app_store
          bundle_identifier: rs.nikolakerkez.fruitcarepro
        vars:
          APP_STORE_APPLE_ID: 1555555551
        flutter: stable
      scripts:
        - name: Set up code signing settings on Xcode project
          script: | 
            xcode-project use-profiles
              --custom-export-options='{"testFlightInternalTestingOnly": true}'
        - name: Get Flutter packages
          script: | 
            flutter pub get
        - name: Install pods
          script: | 
            find . -name "Podfile" -execdir pod install \;
        - name: Flutter analyze
          script: | 
            flutter analyze
        - name: Flutter unit tests
          script: | 
            flutter test
          ignore_failure: true
        - name: Flutter build ipa
          script: | 
            flutter build ipa --release \
              --build-name=1.0.0 \
              --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1)) \
              --export-options-plist=/Users/builder/export_options.plist
      artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - flutter_drive.log
      publishing:
        email:
          recipients:
            - nikolakerkez.rs@gmail.com
          notify:
            success: true
            failure: false
        app_store_connect:
          auth: integration

          # Configuration related to TestFlight (optional)
          # Note: This action is performed during post-processing.
          submit_to_testflight: true
          beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
            - Internal testers

          # Configuration related to App Store (optional)
          # Note: This action is performed during post-processing.
          submit_to_app_store: false