workflows:
  ios-workflow:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: CodeMagic
    environment:
      groups:
        - appstore_credentials
      ios_signing:
        distribution_type: development
        bundle_identifier: rs.nikolakerkez.fruitcarepro
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Remove -G flag from xcconfig files
        script: |
          echo "Removing -index-store-path from xcconfig files..."
          find ios -name "*.xcconfig" -type f -exec sed -i.bak 's/-index-store-path[^ ]*//g' {} \;
      - name: Fix Podfile settings
        script: |
          cd ios
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile
          sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9][0-9]*\.[0-9];/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' Runner.xcodeproj/project.pbxproj
          cd ..
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          find Pods -name "*.xcconfig" -type f -exec sed -i.bak 's/-index-store-path[^ ]*//g' {} \;
          cd ..
      - name: Final cleanup before build
        script: |
          find ios -name "*.xcconfig" -type f -exec sed -i.bak 's/-index-store-path[^ ]*//g' {} \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - nikola.kerkez@icloud.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true