workflows:
  ios-workflow:
    name: iOS TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: rs.nikolakerkez.fruitcarepro
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      
      - name: Fix iOS deployment target
        script: |
          cd ios
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile
          sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9][0-9]*\.[0-9]/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' Runner.xcodeproj/project.pbxproj
          cd ..
      
      - name: Get Flutter packages
        script: flutter pub get
      
      - name: Fix Podfile post_install
        script: |
          cat >> ios/Podfile << 'PODFILE_END'
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
                config.build_settings['ENABLE_BITCODE'] = 'NO'
              end
            end
          end
          PODFILE_END
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build iOS
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true