workflows:
  ios-workflow:
    name: iOS Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: rs.nikolakerkez.fruitcarepro
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Fix Podfile deployment target
        script: |
          cd ios
          
          # Force iOS 13.0 in Podfile
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" Podfile
          
          # Remove old post_install if exists
          sed -i '' '/post_install do |installer|/,/^end$/d' Podfile
          
          # Add comprehensive post_install hook
          cat >> Podfile << 'EOF'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # Force deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      # Fix -G flag issue
      config.build_settings.delete('COMPILER_INDEX_STORE_ENABLE')
      config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
      
      # Disable bitcode
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Other fixes
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
    end
  end
  
  # Fix for Runner target
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |native_target|
      native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
EOF
          
          cd ..
      
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - nikola.kerkez@example.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
