// Top-level build.gradle
buildscript {
    ext.kotlin_version = '2.1.0' // kompatibilno sa novim Flutter pluginom
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1' // za compileSdk 36+
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0' // 
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Flutter očekuje da se svi build outputi nalaze pod <project_root>/build,
// ne pod android/app/build - bez ovoga "flutter build" ne pronalazi .aab/.apk.
rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
