// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbhPUsyJZqhOVIlcVLEeCYR4ypqje3o2A',
    appId: '1:782184044620:web:8dc2d08fdaadf0dab53ce9',
    messagingSenderId: '782184044620',
    projectId: 'fruit-care-pro',
    authDomain: 'fruit-care-pro.firebaseapp.com',
    storageBucket: 'fruit-care-pro.firebasestorage.app',
    measurementId: 'G-ZNV3LLEVFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQSdS20ksta5G5EHKOCLPPwnLvJxAtj5k',
    appId: '1:782184044620:android:ddbe608de0c7d6b1b53ce9',
    messagingSenderId: '782184044620',
    projectId: 'fruit-care-pro',
    storageBucket: 'fruit-care-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyRRmB0zzC0m41X6OEfBc76hXT3jEXi6Y',
    appId: '1:782184044620:ios:f3b8b78413dba988b53ce9',
    messagingSenderId: '782184044620',
    projectId: 'fruit-care-pro',
    storageBucket: 'fruit-care-pro.firebasestorage.app',
    iosBundleId: 'rs.nikolakerkez.fruitcarepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyRRmB0zzC0m41X6OEfBc76hXT3jEXi6Y',
    appId: '1:782184044620:ios:ad45d483727f13fdb53ce9',
    messagingSenderId: '782184044620',
    projectId: 'fruit-care-pro',
    storageBucket: 'fruit-care-pro.firebasestorage.app',
    iosBundleId: 'com.example.bbAgroPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbhPUsyJZqhOVIlcVLEeCYR4ypqje3o2A',
    appId: '1:782184044620:web:bd00ec40938906b7b53ce9',
    messagingSenderId: '782184044620',
    projectId: 'fruit-care-pro',
    authDomain: 'fruit-care-pro.firebaseapp.com',
    storageBucket: 'fruit-care-pro.firebasestorage.app',
    measurementId: 'G-68ZLNCTC36',
  );
}
